### Get all users
GET http://localhost:3000/users

### Get one user
GET http://localhost:3000/users/

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "dally",
  "lastName": "mukuta",
  "email": "dallymukuta12@rdc.com",
  "favoriteColor": "orange",
  "birthday": "1996-02-10"
}

### Update user
PUT http://localhost:3000/users/
Content-Type: application/json

{
  "firstName": "dally",
  "lastName": "mukuta",
  "email": "dallymukuta12@rdc.com",
  "favoriteColor": "orange",
  "birthday": "1996-02-10"
}

### Delete user
DELETE http://localhost:3000/users/68278d349b51af2384d93b77
